notebook_project/notebook_app/urls.py
"""Defines URL patterns for notebook_project."""

from django.urls import path

from . import views

app_name = 'notebook_app'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for changing topic name
    path('edit_topic/<int:topic_id>/', views.edit_topic, name='edit_topic'),
    # Page for adding a new note
    path('new_note/<int:topic_id>/', views.new_note, name='new_note'),
    # Page for editing a note.
    path('edit_note/<int:note_id>/', views.edit_note, name='edit_note'),
    # Delete note
    path('topic/<int:note_id>/<int:topic_id>/', views.delete_note, name='delete_note'),
    # Detail page for a single note.
    path('view_note/<int:note_id>/<int:topic_id>/', views.view_note, name='view_note'),
    # View to delete topic.
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic'),
]

notebook_project/notebook_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('notebook_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notebook_project/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register')
]

notebook_project/notebook_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Topic(models.Model):
    """A topic the user is learning about."""
    topic_name = models.CharField(max_length=50, null=False)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=False)

    class Meta:
        unique_together = ('topic_name', 'owner')

    def __str__(self):
        """Return a string representation of the model."""
        return self.topic_name


class Note(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=False)
    note_name = models.TextField(null=False)
    text = models.TextField(null=True, blank=True)
    img = models.ImageField(upload_to='note_images/', null=True, blank=True, verbose_name='Image')
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('note_name', 'topic')

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text[:50]}..." if len(self.text) > 50 else self.text


# Not implemented
class MultipleImage(models.Model):
    images = models.FileField()

notebook_project/notebook_app/forms.py
from django import forms
from .models import Topic, Note
from django.core.exceptions import ValidationError


class TopicForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self._owner = kwargs.pop('owner', None)
        super(TopicForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Topic
        fields = ['topic_name']

    def clean_topic_name(self):
        owner = self._owner
        topic_name_data = self.cleaned_data['topic_name']

        if Topic.objects.filter(owner_id=owner, topic_name=topic_name_data).count() > 0:
            raise ValidationError(f'Topic name {topic_name_data} already exists')
        return topic_name_data


class NoteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(NoteForm, self).__init__(*args, **kwargs)
        self.fields['topic'].queryset = Topic.objects.filter(owner_id=user)

    class Meta:
        model = Note
        fields = ['note_name', 'text', 'img', 'topic']
        labels = {'note_name': 'Note name', 'text': 'Note:', 'img': 'Image', 'topic': 'Topic list'}
        widgets = {'note_name': forms.TextInput(attrs={'cols': 80, 'rows': 1})}

notebook_project/notebook_app/views.py
from django.shortcuts import render, redirect
from .models import Topic, Note
from .forms import TopicForm, NoteForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


# Create your views here.

def index(request):
    """The home page for Notebook app"""
    viewed_notes = request.session.get("viewed_notes", [])
    notes = []
    for viewed_note in viewed_notes:
        if Note.objects.filter(id=viewed_note).count() > 0:
            note = Note.objects.get(id=viewed_note)
            notes.append(note)
    viewed_notes = notes
    return render(request, 'notebook_app/index.html', {'viewed_notes': viewed_notes}, )


@login_required
def topics(request):
    """Shows topic list"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'notebook_app/topics.html', context)


@login_required
def topic(request, topic_id):
    """shows topic info"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    notes = topic.note_set.order_by('-date_added')
    context = {'topic': topic, 'notes': notes}
    return render(request, 'notebook_app/topic.html', context)


@login_required
def new_topic(request):
    """defines new topic"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST, owner=request.user)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('notebook_app:topics')
    context = {'form': form}
    return render(request, 'notebook_app/new_topic.html', context)

@login_required
def edit_topic(request, topic_id):
    """edits topic name"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = TopicForm(owner=request.user, instance=topic)
    else:
        form = TopicForm(request.POST, owner=request.user, instance=topic)
    if form.is_valid():
        new_topic = form.save(commit=False)
        new_topic.owner = request.user
        new_topic.save()
        return redirect('notebook_app:topics')
    context = {'topic': topic, 'form': form}
    return render(request, 'notebook_app/edit_topic.html', context)


@login_required
def delete_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method == 'POST':
        topic.delete()
    return redirect('notebook_app:topics')


@login_required
def new_note(request, topic_id):
    """adds new note for exact topic"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = NoteForm(user=request.user)
    else:
        form = NoteForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('notebook_app:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'notebook_app/new_note.html', context)


@login_required
def edit_note(request, note_id):
    """Edits note"""
    note = Note.objects.get(id=note_id)
    topic = note.topic
    # topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = NoteForm(user=request.user, instance=note)
    else:
        form = NoteForm(request.POST, request.FILES, user=request.user, instance=note)
        if form.is_valid():
            form.save()
            return redirect('notebook_app:topic', topic_id=topic.id)
    context = {'note': note, 'topic': topic, 'topics': topics, 'form': form}
    return render(request, 'notebook_app/edit_note.html', context)


@login_required
def delete_note(request, note_id, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method == 'POST':
        note = Note.objects.get(id=note_id)
        note.delete()
    return redirect('notebook_app:topic', topic_id=topic.id)


@login_required
def view_note(request, note_id, topic_id):
    """shows note info"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    else:
        viewed_notes = request.session.get("viewed_notes", [])
        if note_id not in viewed_notes:
            viewed_notes.append(note_id)
        request.session["viewed_notes"] = viewed_notes
        if request.method == 'GET':
            note = Note.objects.get(id=note_id)
        context = {'topic': topic, 'note': note}
        return render(request, 'notebook_app/view_note.html', context)


# Not implemented
# def upload_images(request):
#     if request.method == "POST":
#         images = request.FILES.getlist('images')
#         for image in images:
#             MultipleImage.objects.create(images=image)
#     images = MultipleImage.objects.all()
#     return render(request, 'imdex.html', {'images': images})
#

notebook_project/notebook_app/templates/notebook_app/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
  <title>Notebook project</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>

<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'notebook_app:index'%}">
        Notebook project</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'notebook_app:topics'%}">
              Topics</a></li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}.</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
        {% endif %}
      </ul>
    </div>

  </nav>

  <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>

</html>

notebook_project/notebook_app/templates/notebook_app/delete_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

notebook_project/notebook_app/templates/notebook_app/edit_note.html
{% extends "notebook_app/base.html" %}

{% block page_header %}
<h1>Edit note:</h1>
{% endblock page_header %}


{% block content %}

<form action="{% url 'notebook_app:edit_note' note.id %}" method='post' enctype="multipart/form-data">
      {% csrf_token %}

<div class="card mb-3">
  <div class="card-header">
      <div class="card">
          {{form.note_name}}
      </div>
      {% for field, errors in form.errors.items %}
        {% for error in errors %}
            {{errors}}
        {% endfor %}
      {% endfor %}
  </div>

  <div class="card-body">
      <p style="text-align: right">{{note.date_added|date:'M d, Y H:i'}}</p>
      <div class="card mb-3">
        {{form.text}}
      </div>
          <div class="card mb-3"> {{form.topic}}
          </div>
          <div class="mb-3">
              {{form.img}}
          </div>
      <button name='submit' class="btn btn-primary" >save changes</button>
  </div>
</div>
</form>

{% endblock content %}

notebook_project/notebook_app/templates/notebook_app/edit_topic.html
{% extends "notebook_app/base.html" %}

{% block page_header %}
<h1>Edit topic:</h1>
{% endblock page_header %}


{% block content %}
<p>Please enter a new name for topic "{{topic}}"</p>
  <form action="{% url 'notebook_app:edit_topic' topic.id %}" method='post' enctype="multipart/form-data">
    {% csrf_token %}

    <div class="card mb-3">
    {{ form.topic_name }}
    </div>
    {% for field, errors in form.errors.items %}
        {% for error in errors %}
            {{errors}}
        {% endfor %}
    {% endfor %}
    <button name='submit' class="btn btn-primary" >save changes</button>
  </form>

{% endblock content %}

notebook_project/notebook_app/templates/notebook_app/index.html
{% extends "notebook_app/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1 class="display-3">Notebook</h1>

    <p class="lead">
In a constant stream of thoughts we urgently need to write something down
until the worthwhile thought has yet been replaced by another.
<br>We created a notepad app to keep your thoughts safe. Now you can use it to store all of your notes in one place
and easily get rid of already irrelevant information without unnecessary losses.
<br>So let's make some notes ^.^ </p>


    {% if not user.username %}
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
    <a class="btn btn-lg btn-primary" href="{% url 'users:login' %}"
        role="button">Log in &raquo;</a>
    {% else %}
    <a class="btn btn-lg btn-primary" href="{% url 'notebook_app:topics' %}"
    role="button">Go to Topics &raquo;</a>
    {% endif %}

  </div>



{% endblock page_header %}


{% block content %}
{% if viewed_notes %}
<p>Seen recently:</p>
    <ul>
        {% for viewed_note in viewed_notes %}
        <li>
            <a href="{% url 'notebook_app:view_note' viewed_note.id viewed_note.topic_id %}">{{viewed_note.note_name}}</a>
        </li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock content %}

notebook_project/notebook_app/templates/notebook_app/new_note.html
{% extends "notebook_app/base.html" %}

{% block page_header %}

<h1>Add a new note:</h1>

{% endblock page_header %}

{% block content %}

  <form action="{% url 'notebook_app:new_note' topic.id %}" method='post' enctype="multipart/form-data">
    {% csrf_token %}

<div class="card mb-3">
  <div class="card-header">
      <div class="card">
        {{form.note_name}}
      </div>
      {% for field, errors in form.errors.items %}
        {% for error in errors %}
            {{errors}}
        {% endfor %}
      {% endfor %}
  </div>

  <div class="card-body">
      <p style="text-align: right">{{note.date_added|date:'M d, Y H:i'}}</p>
      <div class="card mb-3">
        {{form.text}}
      </div>
      <div class="card mb-3"> {{form.topic}}
          </div>
          <div class="mb-3">
              {{form.img}}
          </div>
      <button name='submit' class="btn btn-primary" >save</button>
  </div>
</div>
</form>

{% endblock content %}

notebook_project/notebook_app/templates/notebook_app/new_topic.html
{% extends "notebook_app/base.html" %}

{% block page_header %}
<h1>Add a new topic</h1>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'notebook_app:new_topic'%}" method='post'>
    {% csrf_token %}
    <div class="card mb-3">
    {{ form.topic_name }}
    </div>
    {% for field, errors in form.errors.items %}
        {% for error in errors %}
            {{errors}}
        {% endfor %}
    {% endfor %}
    <button name='submit' class="btn btn-primary" >Add topic</button>


  </form>

{% endblock content %}

notebook_project/notebook_app/templates/notebook_app/topic.html
{% extends 'notebook_app/base.html' %}

{% block page_header %}
<div class="d-flex bd-highlight">
<div class="p-2 flex-fill bd-highlight"><h1>{{topic}}</h1></div>
<div class="align-self-center" >
      <a href="{% url 'notebook_app:new_note' topic.id %}">Add new note</a>
</div>
</div>
{% endblock page_header %}

{% block content %}

  {% for note in notes %}
    <div class="card mb-3" >
        <h4 class="card-header" style="font-weight: 300">
          <a href="{% url 'notebook_app:view_note' note.id topic.id %}">{{note.note_name}}</a>
        </h4>

      <div class="card-body">
        <p style="text-align: right">{{note.date_added|date:'M d, Y H:i'}}</p>
        <p>{{note.text|linebreaks|truncatechars:300}}</p>
      </div>
    </div>
  {% empty %}
    <p>There are no notes for this topic yet.</p>
  {% endfor %}

{% endblock content %}

notebook_project/notebook_app/templates/notebook_app/topics.html
{% extends "notebook_app/base.html" %}

{% block page_header %}
<div class="d-flex bd-highlight">

<div class="p-2 flex-grow-1 bd-highlight"><h1>Topics</h1></div>
<div class="align-self-center">
  <a href="{% url 'notebook_app:new_topic' %}"> Add new topic</a>
</div>
</div>

{% endblock page_header %}

{% block content %}

        {% for topic in topics %}
        <div class="d-flex bd-highlight card mb-3 card-header"
             style="flex-direction: row; ">
            <div class="p-2 flex-grow-1 bd-highlight w-50"> <h3 style="font-weight: 300">
                <a href="{% url 'notebook_app:topic' topic.id %}">{{ topic|linebreaksbr|wordwrap:50 }}</a></h3>
            </div>
            <div class="p-2 bd-highlight ">
                <form action="{% url 'notebook_app:edit_topic' topic.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary">Edit name</button>
                </form>
            </div>
            <div class="p-2 bd-highlight ">
              <form action="{% url 'notebook_app:delete_topic' topic.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-primary" >Delete topic</button>
              </form>
            </div>
        </div>
        {% empty %}
        <h3>No topics have been added yet.</h3>
        {% endfor %}


{% endblock content %}

notebook_project/notebook_app/templates/notebook_app/view_note.html
{% extends "notebook_app/base.html" %}
{% block content %}

<div class=" card mb-3 " >
    <div class="d-flex bd-highlight card-header" style="flex-direction: row;">
        <div class="p-2 flex-grow-1 bd-highlight w-50">
            <h4>{{note.note_name}}</h4>
        </div>
        <div class="p-2 bd-highlight">
              <form action="{% url 'notebook_app:edit_note' note.id %}" method="get">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-primary">Edit note</button>
              </form>
        </div>
        <div class="p-2 bd-highlight">
              <form action="{% url 'notebook_app:delete_note' note.id topic.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-primary" >Delete note</button>
              </form>
        </div>

    </div>

    <div class="card-body">
        <p style="text-align: right">{{note.date_added|date:'M d, Y H:i'}}</p>
        <p>{{note.text|linebreaks}} </p>
        <p style="text-align: center">
            {% if note.img %}
                <img  class="img-fluid rounded-start" src="{{ note.img.url }}">
            {% endif %}
        </p>
    </div>




</div>
{% endblock content %}